
compiletype=g++
debugtype=-g -o

all:seqlist linklist


seqlist:Seqlist.cpp
		${compiletype} ${debugtype} seqlist Seqlist.cpp

linklist:linklist.cpp
		${compiletype} ${debugtype} linklist linklist.cpp
		



clean:
	rm -f seqlist
	rm -f linklist
